name: "Check signature"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Check signature
        uses: ./.github/actions/checker
